version: "3.7"

services:
  frontend:
    image: th-client
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    image: th-server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
